### ISSUE TITLE
Naming collisions while building DependencyGraph

### ISSUE THREAD

**Issue by andreasbhansen** [react-native-fellowship/react-native-navbar#123] opened 2015-12-16 20:32 UTC
Hey,

I'm getting some naming collisions, seemingly because of the react-native dependencies fighting each other. Any ideas on how to solve this? React Native v. 0.17.0-rc.

```bash
Error building DependencyGraph:
 Error: Naming collision detected: /Users/[...]/Documents/[...]/[...]/node_modules/react-native-navbar/node_modules/react-native/node_modules/react-haste/test/reactComponentExpect.js collides with /Users/[...]/Documents/[...]/[...]/node_modules/react-native/node_modules/react-haste/test/reactComponentExpect.js
    at HasteMap._updateHasteMap (HasteMap.js:123:13)
    at HasteMap.js:94:28
    at tryCallOne (/Users/[...]/Documents/[...]/[...]/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/[...]/Documents/[...]/[...]/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/[...]/Documents/[...]/[...]/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

```

**Comment by grabbou** [comment] 2015-12-17 00:44
Duplicate of #116. @Kureev

**Closed by grabbou** 2015-12-17 00:44 UTC

**Comment by andreasbhansen** [comment] 2015-12-17 08:14
And I thought I had been using ```npm3``` for a long time... Nope! Thanks for the reminder as well :+1:

**Comment by holyxiaoxin** [comment] 2016-03-28 01:19
I'm using `npm3` to install my node modules. But I'm still getting this unfamiliar error.

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: UniversalWorkerNodeHandle
  Paths: /Users/[...]/Workspace/[...]/[...]/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/[...]/Workspace/[...]/[...]/node_modules/react-native-sliding-up-panel/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: UniversalWorkerNodeHandle
  Paths: /Users/[...]/Workspace/[...]/[...]/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/[...]/Workspace/[...]/[...]/node_modules/react-native-sliding-up-panel/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
```
